// This is just a helpful file for myself, so I can run Mongo commands if I ever need to

require('dotenv').config()

const skill = require('./mongo.js')
//const mailer = require('@sendgrid/mail')

const MONGOURL  = process.env.MONGOURL
//const MAILKEY   = process.env.MAILKEY
skill.connect(MONGOURL)

skill.db('collection:Stats', (err, db, col) => {
    console.log(err)

    col.findOneAndUpdate({'steam_id': '76561198099490962'}, {
        $set: {
            'active': Number(new Date()),
            'history': {
              "daily": [
                {
                  "kills": 23,
                  "deaths": 16,
                  "time": 1807,
                  "heads": 4,
                  "rwins": 16,
                  "rounds": 25,
                  "mwins": 1,
                  "matches": 1,
                  "shots": 319,
                  "hits": 71,
                  "damage": 2488,
                  "plants": 2,
                  "contrib": 51,
                  "money": 78800,
                  "mvps": 2,
                  "csnipe": 3,
                  "donation": 7,
                  "g0s": 40,
                  "g2s": 32,
                  "g0h": 7,
                  "g2h": 6,
                  "g0k": 1,
                  "g2k": 2,
                  "g8s": 6,
                  "g8h": 2,
                  "g8k": 1,
                  "g12s": 148,
                  "g12h": 37,
                  "g12k": 12,
                  "g14s": 85,
                  "g14h": 15,
                  "g14k": 5,
                  "g19s": 8,
                  "g19h": 4,
                  "g19k": 2,
                  "date": "2018-05-10T00:00:00.000Z"
                },
                {
                  "kills": 130,
                  "deaths": 103,
                  "time": 5954,
                  "heads": 73,
                  "rwins": 25,
                  "rounds": 44,
                  "mwins": 2,
                  "matches": 6,
                  "shots": 1249,
                  "hits": 346,
                  "damage": 18459,
                  "plants": 2,
                  "contrib": 1041,
                  "money": 116650,
                  "mvps": 9,
                  "knife": 4,
                  "flash": 3,
                  "csnipe": 14,
                  "backfire": 2,
                  "doms": 3,
                  "overkill": 6,
                  "donation": 2,
                  "wins_dust2": 14,
                  "rnds_dust2": 17,
                  "g0s": 27,
                  "g2s": 232,
                  "g0h": 4,
                  "g2h": 86,
                  "g2k": 22,
                  "g3s": 2,
                  "g4s": 8,
                  "g4h": 2,
                  "g8s": 115,
                  "g10s": 5,
                  "g8h": 41,
                  "g10h": 1,
                  "g8k": 21,
                  "g11s": 69,
                  "g12s": 474,
                  "g11h": 18,
                  "g12h": 108,
                  "g11k": 5,
                  "g12k": 42,
                  "g14s": 79,
                  "g15s": 3,
                  "g14h": 27,
                  "g14k": 5,
                  "g16s": 16,
                  "g17s": 19,
                  "g16h": 3,
                  "g17h": 4,
                  "g16k": 2,
                  "g17k": 2,
                  "g18s": 47,
                  "g18h": 26,
                  "g18k": 23,
                  "g21s": 80,
                  "g21h": 23,
                  "g21k": 3,
                  "g30s": 48,
                  "g31s": 25,
                  "g30h": 1,
                  "g31h": 5,
                  "g31k": 1,
                  "date": "2018-04-26T00:00:00.000Z"
                },
                {
                  "kills": 113,
                  "deaths": 81,
                  "time": 3253,
                  "heads": 55,
                  "rwins": 6,
                  "rounds": 7,
                  "matches": 5,
                  "shots": 1699,
                  "hits": 463,
                  "damage": 15461,
                  "plants": 1,
                  "contrib": 1580,
                  "money": 5550,
                  "mvps": 5,
                  "csnipe": 14,
                  "doms": 7,
                  "revs": 1,
                  "overkill": 9,
                  "wins_cbble": 1,
                  "wins_nuke": 3,
                  "rnds_cbble": 1,
                  "rnds_nuke": 4,
                  "g2s": 159,
                  "g2h": 58,
                  "g2k": 14,
                  "g3s": 75,
                  "g4s": 65,
                  "g3h": 13,
                  "g4h": 17,
                  "g3k": 1,
                  "g4k": 4,
                  "g6s": 101,
                  "g6h": 32,
                  "g6k": 8,
                  "g8s": 54,
                  "g10s": 7,
                  "g8h": 24,
                  "g10h": 5,
                  "g8k": 12,
                  "g10k": 2,
                  "g11s": 16,
                  "g11h": 3,
                  "g11k": 1,
                  "g14s": 261,
                  "g15s": 1,
                  "g14h": 73,
                  "g15h": 1,
                  "g14k": 20,
                  "g15k": 1,
                  "g17s": 244,
                  "g17h": 80,
                  "g17k": 24,
                  "g18s": 5,
                  "g18h": 2,
                  "g18k": 2,
                  "g20s": 35,
                  "g20h": 13,
                  "g20k": 5,
                  "g22s": 91,
                  "g23s": 107,
                  "g22h": 20,
                  "g23h": 27,
                  "g22k": 2,
                  "g23k": 3,
                  "g24s": 95,
                  "g25s": 11,
                  "g24h": 22,
                  "g25h": 4,
                  "g24k": 3,
                  "g27s": 117,
                  "g27h": 13,
                  "g27k": 2,
                  "g28s": 30,
                  "g28h": 7,
                  "g28k": 1,
                  "g30s": 176,
                  "g30h": 45,
                  "g30k": 6,
                  "g32s": 49,
                  "g32h": 8,
                  "g32k": 2,
                  "date": "2018-03-25T00:00:00.000Z"
                },
                {
                  "kills": 30,
                  "deaths": 33,
                  "time": 1021,
                  "heads": 14,
                  "rwins": 2,
                  "rounds": 2,
                  "mwins": 1,
                  "matches": 2,
                  "shots": 333,
                  "hits": 115,
                  "damage": 3647,
                  "contrib": 204,
                  "csnipe": 5,
                  "g2s": 214,
                  "g2h": 83,
                  "g2k": 18,
                  "g3s": 70,
                  "g3h": 21,
                  "g3k": 7,
                  "g6s": 40,
                  "g6h": 11,
                  "g6k": 4,
                  "g15s": 9,
                  "g15h": 2,
                  "g15k": 1,
                  "date": "2018-03-24T00:00:00.000Z"
                },
                {
                  "kills": 105,
                  "deaths": 77,
                  "time": 5706,
                  "heads": 39,
                  "rwins": 41,
                  "rounds": 77,
                  "mwins": 1,
                  "matches": 3,
                  "shots": 1703,
                  "hits": 356,
                  "damage": 15461,
                  "plants": 5,
                  "hostage": 1,
                  "contrib": 164,
                  "money": 240300,
                  "mvps": 10,
                  "knife": 5,
                  "csnipe": 3,
                  "backfire": 5,
                  "pistolwin": 4,
                  "donation": 5,
                  "g0s": 26,
                  "g0h": 5,
                  "g0k": 1,
                  "g5s": 59,
                  "g6s": 60,
                  "g5h": 16,
                  "g6h": 22,
                  "g5k": 1,
                  "g6k": 4,
                  "g8s": 16,
                  "g10s": 5,
                  "g8h": 6,
                  "g10h": 1,
                  "g8k": 3,
                  "g11s": 25,
                  "g12s": 480,
                  "g11h": 12,
                  "g12h": 99,
                  "g11k": 2,
                  "g12k": 29,
                  "g14s": 299,
                  "g15s": 34,
                  "g14h": 51,
                  "g15h": 15,
                  "g14k": 11,
                  "g15k": 8,
                  "g16s": 122,
                  "g17s": 29,
                  "g16h": 19,
                  "g17h": 10,
                  "g16k": 4,
                  "g17k": 2,
                  "g18s": 10,
                  "g18h": 4,
                  "g18k": 3,
                  "g21s": 388,
                  "g21h": 84,
                  "g21k": 26,
                  "g24s": 9,
                  "g25s": 53,
                  "g24h": 3,
                  "g25h": 1,
                  "g24k": 1,
                  "g30s": 32,
                  "g30h": 4,
                  "g30k": 1,
                  "g35s": 1,
                  "date": "2018-03-21T06:00:00.000Z"
                }
              ],
              "monthly": []
          },
          'grand': {
            "time": 17741,
            "kills": 401,
            "deaths": 310,
            "heads": 185,
            "plants": 10,
            "defuse": 0,
            "hostage": 1,
            "rounds": 155,
            "rwins": 90,
            "matches": 17,
            "mwins": 5,
            "shots": 5303,
            "hits": 1351,
            "damage": 55516,
            "money": 441300,
            "contrib": 3040,
            "mvps": 26,
            "knife": 9,
            "nades": 0,
            "fires": 0,
            "doms": 10,
            "revs": 1,
            "overkill": 15,
            "pistolwin": 4,
            "donation": 14,
            "wins_cbble": 1,
            "wins_dust2": 14,
            "wins_inferno": 0,
            "wins_nuke": 3,
            "wins_train": 0,
            "rnds_cbble": 1,
            "rnds_dust2": 17,
            "rnds_inferno": 0,
            "rnds_nuke": 4,
            "rnds_train": 0,
            "flash": 3
          }
        }}, (err, result) => {
        console.log(result.ok)
        db.close()
    })
})


/*mailer.setApiKey(MAILKEY)
mailer.send({
    to: 'devteam@csgo-skill.com',
    from: 'Skill Bot <skillbot@csgo-skill.com>',
    subject: 'Test Email',
    html: 'Hey!<br>Did you <b>get this</b>?'
}).then(() => {
    console.log('Email sent!')
})
.catch(error => {
    console.error(`Email failed: ${error}`)
})*/
